# Prometheus sd_config setup
global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:

  - job_name: cassandra
    file_sd_configs:
    - files:
      - /opt/apps/monitor/config/prometheus/sd_configs/*cassandra.json

  - job_name: kafka
    file_sd_configs:
    - files:
      - /opt/apps/monitor/config/prometheus/sd_configs/*kafka.json

  - job_name: fabric
    file_sd_configs:
    - files:
      - /opt/apps/monitor/config/prometheus/sd_configs/*fabric.json

  - job_name: node_exporter
    static_configs:
    - targets: ['localhost:9100']